version: '3'
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    container_name: datascience-notebook
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./:/home/jovyan/work
